run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - typecheck
    - gocyclo
    - gocognit
linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 10
